name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

env:
  VOLTA_FEATURE_PNPM: 1
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: volta-cli/action@d253558a6e356722728a10e9a469190de21a83ef # v4
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test

  embroider:
    strategy:
      matrix:
        scenario: ['safe', 'optimized']

    name: Embroider ${{ matrix.scenario }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: volta-cli/action@d253558a6e356722728a10e9a469190de21a83ef # v4
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install
      - run: pnpm build
      - run: pnpm ember try:one embroider-${{ matrix.scenario }} --skip-cleanup
        working-directory: packages/ember-app
